Activate kc-newbackup as kc-backup

diff --git a/bin/kc-backup b/bin/kc-backup
--- a/bin/kc-backup
+++ b/bin/kc-backup
@@ -4,18 +4,27 @@ sf_start
 
 . /opt/kc/etc/config
 
-GLUSTER_VOLUME="cust"
 MPOINT=/backup
 NAME="kvm-bup"
 HOSTS=$( cat ${KC_TSP_DIR}/config/hosts.conf )
-EXCLUDE="*_temp_disk.qcow2"
-SSH_OPT=""
+KC_BACKUP_EXCLUDE=""
+
+DEV=""
 
 #############################
 _usage()
 {
   if [ "$1" = "" ] ; then
-    echo "  usage: `basename $0` mount|umount|simul|backup [vm]"
+    echo ""
+    echo "usage:"
+    echo ""
+    echo "`basename $0` mount|umount"
+    echo ""
+    echo "`basename $0` backup [<domain>]"
+    echo "`basename $0` restore <domain>"
+    echo "`basename $0` delete <domain> # delete domain backup from backup device"
+    echo "`basename $0` info <domain>   # virtnbdbackup debug infos"
+    echo ""
     exit 0
   fi
 }
@@ -37,6 +46,8 @@ _mount()
     DEV=`blkid  -U $UUID`
     ret=$?
     if [ "$ret" = "0" ] ; then
+      mkdir -p /var/kc
+      echo "$DEV" > /var/kc/device
       cryptsetup luksOpen $DEV $NAME < ${KC_TSP_DIR}/config/backup-passwd.conf
       mount /dev/mapper/$NAME $MPOINT
       . $MPOINT/INFO.cfg 
@@ -57,6 +68,33 @@ _umount()
   umount $MPOINT
   cryptsetup luksClose $NAME
   echo "backup device: <${INFO_HD_NAME}> successfully unmounted from <$MPOINT>"
+  if [ -f /var/kc/device  ] ; then
+    hdparm -y  $(cat /var/kc/device) 2>/dev/null # spin-off disk
+  fi
+}
+#############################
+_info()
+{
+  DOM="$1"
+  printf "#\n#\n#\n"
+  unset imgs ; declare -A imgs
+  eval $( virsh domblklist $DOM --details | awk '/file +disk/ {print "imgs["$3"]="$4}' )
+  for dev in ${!imgs[@]}; do
+    echo $dev : ${imgs[$dev]}
+    qemu-img info -U ${imgs[$dev]}
+  done
+
+  printf "#\n# libvirt chackpoint infos in /var/lib/libvirt/qemu/checkpoint/$DOM/:\n#\n"
+  ls -la /var/lib/libvirt/qemu/checkpoint/$DOM/
+
+  printf "#\n# virtnbdbackup checkpoint infos in /tsp0/sync/backup/$DOM/:\n#\n"
+  ls -la /tsp0/sync/backup/$DOM/
+
+  printf "#\n# libvirt chackpoint infos:\n#\n"
+  vircpt -d $DOM list
+
+  printf "#\n# virsh checkpoint-list for $DOM:\n#\n"
+  virsh checkpoint-list $DOM
 }
 #############################
 _status()
@@ -76,6 +114,7 @@ _status()
 CMD="$1"
 VMB="$2"
 
+
 if [ "$CMD" = "mount" ] ; then
   _mount
   exit 0
@@ -84,156 +123,183 @@ if [ "$CMD" = "umount" ] ; then
   _umount
   exit 0
 fi
+if [ "$CMD" = "info" ] ; then
+  if [ "$VMB" = "" ] ; then
+     echo "error: domain not given!"
+     exit 1
+  fi
+  _info $VMB
+  exit 0
+fi 
+
 _usage $CMD
-if [ "$CMD" != "backup" -a "$CMD" != "simul" ] ; then
+if [ "$CMD" != "backup" -a "$CMD" != "restore"  -a "$CMD" != "delete" ] ; then
   echo "unkomwn command given"
+  exit 1
+fi
+if [ "$CMD" = "restore" -a "$VMB" = "" ] ; then
+  echo "error: domain not given!"
   exit 1
 fi
 
 date
 _status
 _mount
-#
-# cleanup orphaned backup files from backup device
-#
-list=$(find /backup/ -type f -name ".*qcow2.*")
-for i in $list ; do
-  rm $i
-done
-#
-# backup rfs-changes
-#
-for host in $HOSTS ; do
-  mkdir -p ${KC_TSP_DIR}/rfs-backup/${h}
-  ssh ${SSH_OPT} -q ${KC_USER}@${host} "rsync -av --files-from=/opt/kc/etc/rfs-changes  / ${KC_TSP_DIR}/rfs-backup/${host}"
-done
-rsync -av ${KC_TSP_DIR}/rfs-backup/ $MPOINT/rfs-backup
-#
-# backup ISOs
-#
-if [ -d  ${KC_TSP_DIR}/ISOs ] ; then
-  mkdir -p $MPOINT/ISOs
-  rsync -av ${KC_TSP_DIR}/ISOs/    $MPOINT/ISOs
+
+if [ ! -f "${KC_TSP_DIR}/config/kc-backup.conf" ] ; then
+  echo "error: missing definition file <${KC_TSP_DIR}/config/kc-backup.conf>."
+  exit 1
+fi
+. ${KC_TSP_DIR}/config/kc-backup.conf
+if [ "$KC_BACKUP_AREA" = "" ] ; then
+  echo "error: backup area <KC_BACKUP_AREA> not set in <${KC_TSP_DIR}/config/kc-backup.conf>."
+  exit 1
 fi
 #
-# backup kc config
+# delete domain from usb
 #
-mkdir -p $MPOINT/config
-rsync -av ${KC_TSP_DIR}/config/  $MPOINT/config
+if [ "$CMD" = "delete" ] ; then
+  if [ "$VMB" = ""  ] ; then
+    echo "error: nod domain given"
+    _umount
+    exit 1
+  fi 
+  rm -rvf $MPOINT/$KC_BACKUP_AREA/domains/$VMB
+  _umount
+  exit 0
+fi
 #
-# backup vms
+# restore domain
 #
-echo "===================================================================="
-  for h in $HOSTS ; do
-    vms=$( ssh ${SSH_OPT} -q ${KC_USER}@${h} "virsh list --all --name" )
-    for vm in $vms ; do
-        if [[ $vm == \[*:kvm[1-9]\] ]] ; then
-          continue ;
-        fi
-        state=$( ssh ${SSH_OPT} -q ${KC_USER}@${h} "virsh domstate ${vm}" )
-        _DATE=$( date +"%Y-%m-%d %H:%M:%S" )
-        echo "####################################################"
-        echo "#  $vm @ ${h} ($state) ${_DATE}"
-        echo "####################################################"
-        # Get list of disk names and image paths
-        unset imgs ; declare -A imgs
-        disc=""
-        disc=$( ssh ${SSH_OPT} -q ${KC_USER}@${h}  virsh domblklist ${vm} --details | awk '/file +disk/ {print $3}' )
-        eval $( ssh ${SSH_OPT} -q ${KC_USER}@${h}  virsh domblklist ${vm} --details | awk '/file +disk/ {print "imgs["$3"]="$4}' )
-        #
-        # Test if there exists already a file with extension .backup
-        #
-        for d in ${disc[@]}; do
-            img=${imgs[${d}]}
-            img=${img%.qcow2} ; img=${img%.img}
-            #echo check if $img exists
-            if [ -f ${img}.backup ] ; then
-               echo "error: ${img}.backup from VM ${vm} already exists"
-               _umount
-               sf_set_error
-               sf_end
-            fi
-        done
-        if [ "$VMB" = "$vm" -o "$VMB" = "" ] ; then
-          if [ "$CMD" = "simul" ] ; then
-            echo mkdir -p $MPOINT/domains/${vm}
-            echo "ssh ${SSH_OPT} -q ${KC_USER}@${h} "virsh dumpxml $vm"  > $MPOINT/domains/${vm}/${vm}.xml"
-          else
-            mkdir -p $MPOINT/domains/${vm}
-            ssh ${SSH_OPT} -q ${KC_USER}@${h} "virsh dumpxml $vm"  > $MPOINT/domains/${vm}/${vm}.xml
-          fi
-          if [ "$state" != "shut off" ] ; then
-            QPAR="--quiesce"
-            ssh ${SSH_OPT} -q ${KC_USER}@${h} "virsh domtime ${vm}" >/dev/null 2>&1
-            if [ "$?" != "0" ] ; then
-                QPAR=""
-                echo "warning: snapshot-create without quiesce!!!"
-            fi
-            if [ "$CMD" = "simul" ] ; then
-              echo ssh ${SSH_OPT} -q ${KC_USER}@${h} "virsh snapshot-create-as ${vm} backup --disk-only --atomic --no-metadata ${QPAR}" 
-            else
-              ssh ${SSH_OPT} -q ${KC_USER}@${h} "virsh snapshot-create-as ${vm} backup --disk-only --atomic --no-metadata ${QPAR}" 
-            fi
-          fi
-          for d in ${disc[@]}; do
-            img=${imgs[${d}]}
-            if [[ "$(basename $img)" == $EXCLUDE ]]; then
-              echo "skipping backup of image: <$img>, because of EXCLUDE setting <$EXCLUDE>"
-            else
-              if [ "$CMD" = "simul" ] ; then
-                echo rsync -av ${img} $MPOINT/domains/${vm}/
-              else
-                echo "copy ${img} to $MPOINT/domains/${vm}/ ..."
-                rsync -av ${img} $MPOINT/domains/${vm}/   # --progress
-              fi
-            fi
-            if [ "$state" != "shut off" ] ; then
-              if [ "$CMD" = "simul" ] ; then
-                echo ssh ${SSH_OPT} -q ${KC_USER}@${h} "virsh blockcommit ${vm} ${d} --active --wait --pivot"
-              else
-                ssh ${SSH_OPT} -q ${KC_USER}@${h} "virsh blockcommit ${vm} ${d} --active --wait --pivot"
-
-                # check, if commit was successful
-                chk=$( ssh ${SSH_OPT} -q ${KC_USER}@${h}  "virsh domblklist ${vm} --details" | awk "/file +disk +${d}/ {print \$4}"  )
-                if [ "${chk}" != "${img}" ] ; then
-                  echo "error: blockcommit for image: <${img}>"
-                  _umount
-                  sf_set_error
-                  sf_end
-                fi 
-                img=${img%.qcow2} ; img=${img%.img} 
-                echo "remove snapshot image: <${img}.backup>"
-                rm -f ${img}.backup
-              fi
-            fi
-          done
-          ssh ${SSH_OPT} -q ${KC_USER}@${h}  "virsh domblklist ${vm} --details"
-        fi
-    done
-  done
-echo "===================================================================="
-#find   $MPOINT -ls
-df -h  $MPOINT
-usage_pcent=$(df -h $MPOINT --output="pcent" | grep -v "Use" | sed "s| ||g" )
-_umount
-date
-if [ -e ${KC_TSP_DIR}/config/kc-backup.conf ] ; then
-  . ${KC_TSP_DIR}/config/kc-backup.conf
-  FI=${KC_TSP_DIR}/sync/backup/kc-backup.rep
-  if [ ! -f ${FI} ] ; then
-    mkdir -p `dirname ${FI}`
-    touch ${FI}
+if [ "$CMD" = "restore" ] ; then
+  kvmc --domain=$VMB rm complete
+  virtnbdrestore -D -N $VMB -i $MPOINT/$KC_BACKUP_AREA/domains/$VMB -o ${KC_TSP_DIR}/images
+  ret=$?
+  if [ "$ret" != "0" ] ; then
+    echo "error: virtnbdrestore returns <$ret>"
+    _umount
+    exit 1
   fi
-  DAT=$(date +"%Y-%m-%d %H:%M:%S")
-  sed -i "1s/^/${DAT} ${INFO_HD_NAME} [${usage_pcent}]\n/" ${FI}
-  subject="kc-backup @ `hostname`"
-  swaks --to ${KC_BACKUP_TO} --from ${KC_BACKUP_FROM} \
-        -s   ${KC_BACKUP_SMTP} \
-        --header "Subject: $subject" \
-        --attach-type "text/plain" --attach-body @${FI} \
-        --attach-type "text/plain" --attach @${FI} \
-        -S 2
+  kvmc --domain=$VMB up
+  rm -rvf  ${KC_TSP_DIR}/sync/backup/$VMB
+  mkdir -p ${KC_TSP_DIR}/sync/backup/$VMB
+  rm -f    ${KC_TSP_DIR}/sync/backup/$VMB.conf  # mark this backup for removal on next backup, so full backup will be done
+  _umount
+  exit 0
 fi
-
+#
+# backup
+#
+if [ "$CMD" = "backup" ] ; then
+  if [ "$VMB" = "" ] ; then # only for complete backup
+    #
+    # backup rfs-changes
+    #
+    for host in $HOSTS ; do
+      mkdir -p ${KC_TSP_DIR}/rfs-backup/${h}
+      ssh -q ${KC_USER}@${host} "rsync -av --files-from=/opt/kc/etc/rfs-changes  / ${KC_TSP_DIR}/rfs-backup/${host}"
+    done
+    rsync -av ${KC_TSP_DIR}/rfs-backup/ $MPOINT/$KC_BACKUP_AREA/rfs-backup
+    #
+    # backup ISOs
+    #
+    if [ -d  ${KC_TSP_DIR}/ISOs ] ; then
+      mkdir -p $MPOINT/$KC_BACKUP_AREA/ISOs
+      rsync -av --delete ${KC_TSP_DIR}/ISOs/   $MPOINT/$KC_BACKUP_AREA/ISOs
+    fi
+    #
+    # backup kc config
+    #
+    mkdir -p $MPOINT/$KC_BACKUP_AREA/config
+    rsync -av ${KC_TSP_DIR}/config/ $MPOINT/$KC_BACKUP_AREA/config
+  fi
+  #
+  # backup vms
+  #
+  mkdir -p ${KC_TSP_DIR}/sync/backup
+  echo "===================================================================="
+  vms=$( virsh list --all --name )
+  for vm in $vms ; do
+    if [[ $vm == \[*:kvm[1-9]\] ]] ; then
+      continue ;
+    fi
+    state=$( virsh domstate ${vm} )
+    _DATE=$( date +"%Y-%m-%d %H:%M:%S" )
+    echo "####################################################"
+    echo "#  $vm @ ${h} ($state) ${_DATE}"
+    echo "####################################################"
+    # Get list of disk names and image paths
+    unset imgs ; declare -A imgs
+    disc=""
+    disc=$( virsh domblklist ${vm} --details | awk '/file +disk/ {print $3}' )
+    eval $( virsh domblklist ${vm} --details | awk '/file +disk/ {print "imgs["$3"]="$4}' )
+    if [ "$VMB" = "$vm" -o "$VMB" = "" ] ; then
+        #
+        # remove former backups from device, if new device detected
+        #
+      last_device=$( cat ${KC_TSP_DIR}/sync/backup/$vm.conf 2>/dev/null )
+      if [ "$last_device"  != "${INFO_HD_NAME}" ] ; then
+        rm -rvf  $MPOINT/$KC_BACKUP_AREA/domains/$vm 
+        mkdir -p $MPOINT/$KC_BACKUP_AREA/domains/$vm
+      fi
+      #
+      # exclude images
+      #
+      exclude_disks=""
+      for d in ${disc[@]}; do
+        img=${imgs[${d}]}
+        if [[ "$(basename $img)" == $KC_BACKUP_EXCLUDE ]]; then
+          exclude_disks="${exclude_disks},$d"
+          echo "skipping backup of image: <$img>, because it of KC_BACKUP_EXCLUDE setting <$KC_BACKUP_EXCLUDE>"
+        fi
+      done
+      if [ "${exclude_disks}" != "" ] ; then
+        exclude_disks=${exclude_disks%,}
+        exclude_disks="-x $exclude_disks"
+      fi  
+      echo "jetzt backup für Domain <$vm> durchführen..."
+      mkdir -p ${KC_TSP_DIR}/sync/backup/$vm
+      virtnbdbackup  -d $vm -l auto ${exclude_disks} -o $MPOINT/$KC_BACKUP_AREA/domains/$vm --checkpointdir ${KC_TSP_DIR}/sync/backup/$vm
+      ret=$?
+      if [ "$ret" != "0" ] ; then
+        echo "error: virtnbdbackup returns <$ret>"
+        _umount
+        exit 1
+      fi
+      # store backup device name
+      echo "${INFO_HD_NAME}" > ${KC_TSP_DIR}/sync/backup/$vm.conf
+      echo "backup für Domain <$vm> ist durchgeführt"
+    fi
+  done
+  echo "===================================================================="
+  df -h  $MPOINT
+  usage_pcent=$(df -h $MPOINT --output="pcent" | grep -v "Use" | sed "s| ||g" )
+  echo "##############################"
+  tree $MPOINT/$KC_BACKUP_AREA
+  echo "##############################"
+  tree ${KC_TSP_DIR}/sync/backup
+  echo "##############################"
+  _umount
+  date
+  if [ "$VMB" = "" ] ; then # only for complete backup
+    if [ -e ${KC_TSP_DIR}/config/kc-backup.conf ] ; then
+      . ${KC_TSP_DIR}/config/kc-backup.conf
+      FI=${KC_TSP_DIR}/sync/backup/kc-backup.rep
+      if [ ! -f ${FI} ] ; then
+        mkdir -p `dirname ${FI}`
+        touch ${FI}
+      fi
+      DAT=$(date +"%Y-%m-%d %H:%M:%S")
+      sed -i "1s/^/${DAT} ${INFO_HD_NAME} [${usage_pcent}] new\n/" ${FI}
+      subject="kc-backup @ `hostname`"
+      swaks --to ${KC_BACKUP_TO} --from ${KC_BACKUP_FROM} \
+            -s   ${KC_BACKUP_SMTP} \
+            --header "Subject: $subject" \
+            --attach-type "text/plain" --attach-body @${FI} \
+            --attach-type "text/plain" --attach @${FI} \
+            -S 2
+    fi
+  fi
+fi
 sf_end
 
