Start with kc-sprarsify.

diff --git a/bin/kc-sparsify b/bin/kc-sparsify
--- a/bin/kc-sparsify
+++ b/bin/kc-sparsify
@@ -93,24 +93,36 @@ _status
         disc=$( ssh -q ${KC_USER}@${h}  "virsh domblklist ${vm} --details" | awk '/^file +disk/ {print $3}' )
         eval $( ssh -q ${KC_USER}@${h}  "virsh domblklist ${vm} --details" | awk '/^file +disk/ {print "imgs["$3"]="$4}' )
         if [ "$VMB" = "$vm" -o "$VMB" = "" ] ; then
-          if [ "$CMD" = "simul" ] ; then
+          ssh -q ${KC_USER}@${h}  "virsh domblklist ${vm} --details"
+          if [ "$state" != "shut off" ] ; then
             echo ssh -q ${KC_USER}@${h} "virsh shutdown  $vm"
-          else
-            echo ssh -q ${KC_USER}@${h} "virsh shutdown  $vm"
+            if [ "$CMD" = "real" ] ; then
+              ssh -q ${KC_USER}@${h} "virsh shutdown  $vm"
+            fi
           fi
           for d in ${disc[@]}; do
             img=${imgs[${d}]}
-            if [[ "$(basename $img)" == $EXCLUDE ]]; then
-              echo "skipping backup of image: <$img>, because of EXCLUDE setting <$EXCLUDE>"
-            else
-              if [ "$CMD" = "simul" ] ; then
-                echo "virt-sparsify --inline ${img}"
-              else
-                echo "virt-sparsify --inline ${img}"
+            #if [[ "$(basename $img)" == $EXCLUDE ]]; then
+            #  echo "skipping backup of image: <$img>, because of EXCLUDE setting <$EXCLUDE>"
+            #else
+              echo ssh -q ${KC_USER}@${h} "virt-sparsify --in-place ${img}"
+              if [ "$CMD" = "real" ] ; then
+                ssh -q ${KC_USER}@${h} "virt-sparsify --in-place ${img}"
+                ret=$?
+                if [ "$ret" != "0" ] ; then
+                   echo "ERROR = $ret !!!!!!"
+                   exit $ret
+                fi
               fi
-            fi
+            #fi
           done
-          ssh -q ${KC_USER}@${h}  "virsh domblklist ${vm} --details"
+          if [ "$state" != "shut off" ] ; then
+            echo ssh -q ${KC_USER}@${h} "virsh start  $vm"
+            if [ "$CMD" = "real" ] ; then
+              ssh -q ${KC_USER}@${h} "virsh start  $vm"
+            fi
+          fi
+
         fi
     done
   done
